# Generated by Django 5.0.6 on 2024-08-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='capacidad',
        ),
        migrations.AddField(
            model_name='tipohabitacion',
            name='capacidad_maxima',
            field=models.IntegerField(default=1),
        ),
    ]
