# Generated by Django 5.0.6 on 2025-01-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0003_rename_caracteristica_caracteristicahab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='numero',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
