# Generated by Django 5.0.6 on 2025-01-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0004_alter_habitacion_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('limpieza', 'En Limpieza'), ('mantenimiento', 'En Mantenimiento'), ('reservada', 'Reservada')], default='disponible', max_length=20),
        ),
    ]
