# Generated by Django 5.0.6 on 2025-01-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0005_alter_habitacion_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='fotos/')),
            ],
        ),
        migrations.RemoveField(
            model_name='tipohabitacion',
            name='fotos',
        ),
        migrations.AddField(
            model_name='tipohabitacion',
            name='fotos',
            field=models.ManyToManyField(blank=True, to='habitaciones.fotohabitacion'),
        ),
    ]
