# Generated by Django 5.0.6 on 2025-01-28 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0006_fotohabitacion_remove_tipohabitacion_fotos_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CaracteristicaHab',
            new_name='ServicioHab',
        ),
        migrations.RenameField(
            model_name='tipohabitacion',
            old_name='caracteristicas',
            new_name='servicios',
        ),
    ]
