# Generated by Django 5.0.6 on 2025-01-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0007_rename_caracteristicahab_serviciohab_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciohab',
            name='icono',
            field=models.ImageField(blank=True, upload_to='iconos/'),
        ),
    ]
