# Generated by Django 5.0.6 on 2025-02-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0008_alter_serviciohab_icono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciohab',
            name='icono',
            field=models.CharField(max_length=50),
        ),
    ]
