# Generated by Django 5.0.6 on 2025-02-13 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0009_alter_serviciohab_icono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotohabitacion',
            name='imagen',
            field=models.ImageField(upload_to='fotos_habitaciones/'),
        ),
    ]
