# Generated by Django 5.0.6 on 2025-02-13 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0010_alter_fotohabitacion_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fotohabitacion',
            options={'ordering': ['id']},
        ),
    ]
