# Generated by Django 5.0.6 on 2025-03-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0013_alter_habitacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='serviciohab',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tipohabitacion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
