# Generated by Django 5.0.6 on 2025-04-02 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0014_habitacion_activo_serviciohab_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='tipo_habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='habitaciones.tipohabitacion'),
        ),
        migrations.AlterField(
            model_name='tipohabitacion',
            name='capacidad_maxima',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
