# Generated by Django 5.0.6 on 2025-04-14 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0015_alter_habitacion_tipo_habitacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipohabitacion',
            name='descripcion_camas',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tipohabitacion',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
