# Generated by Django 5.0.6 on 2025-04-15 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0016_tipohabitacion_descripcion_camas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipohabitacion',
            name='descripcion_camas',
        ),
        migrations.CreateModel(
            name='CamaTipoHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cama', models.CharField(choices=[('King', 'Cama King'), ('Double', 'Cama Doble'), ('Twin', 'Cama Twin')], max_length=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('tipo_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='habitaciones.tipohabitacion')),
            ],
        ),
    ]
