# Generated by Django 5.0.6 on 2025-04-15 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0017_remove_tipohabitacion_descripcion_camas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camatipohabitacion',
            name='tipo_habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitaciones.tipohabitacion'),
        ),
    ]
