# Generated by Django 5.0.6 on 2025-04-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0018_alter_camatipohabitacion_tipo_habitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camatipohabitacion',
            name='tipo_cama',
            field=models.CharField(choices=[('King', 'King'), ('Double', 'Double'), ('Twin', 'Twin')], max_length=10),
        ),
    ]
