# Generated by Django 5.0.6 on 2025-04-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0019_alter_camatipohabitacion_tipo_cama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='estado',
            field=models.CharField(choices=[('Habilitada', 'Habilitada'), ('Ocupada', 'Ocupada'), ('En limpieza', 'En Limpieza'), ('Mantenimiento', 'En Mantenimiento')], default='Disponible', max_length=20),
        ),
    ]
