# Generated by Django 5.0.6 on 2025-04-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0020_alter_habitacion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='estado',
            field=models.CharField(choices=[('Habilitada', 'Habilitada'), ('Ocupada', 'Ocupada'), ('En limpieza', 'En Limpieza')], default='Disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviciohab',
            name='icono',
            field=models.CharField(default='fa-check', max_length=50),
        ),
    ]
