# Generated by Django 5.0.6 on 2025-04-02 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitaciones', '0015_alter_habitacion_tipo_habitacion_and_more'),
        ('usuarios', '0002_alter_huesped_usuario_huesped_dni_pasaporte_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_check_in_esperada', models.DateField()),
                ('fecha_check_out_esperada', models.DateField()),
                ('cantidad_huespedes', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada'), ('Finalizada', 'Finalizada')], default='pendiente', max_length=15)),
                ('fecha_check_in_efectuada', models.DateField()),
                ('fecha_check_out_efectuada', models.DateField()),
                ('total_reserva', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('habitaciones', models.ManyToManyField(to='habitaciones.habitacion')),
                ('huesped', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.huesped')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
