# Generated by Django 5.0.6 on 2025-04-20 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_reserva_cantidad_huespedes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia Bancaria')], max_length=25)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='total_reserva',
        ),
        migrations.AddField(
            model_name='reserva',
            name='pago',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.PROTECT, to='reservas.pago'),
            preserve_default=False,
        ),
    ]
