# Generated by Django 5.0.6 on 2025-04-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_pago_remove_reserva_total_reserva_reserva_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='activo',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_check_in_efectuada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_check_out_efectuada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
