# Generated by Django 5.0.6 on 2025-04-21 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_remove_reserva_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='pago',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reservas.pago'),
        ),
    ]
