# Generated by Django 5.0.6 on 2025-04-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_reserva_monto_total_alter_reserva_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada'), ('Finalizada', 'Finalizada')], default='Pendiente', max_length=15),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_check_in_efectuada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_check_out_efectuada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
